MeTee: linux: Include poll.h instead of sys/poll.h
fix compilation error with musl C library:

 error: #warning redirecting incorrect #include <sys/poll.h> to <poll.h>

Signed-off-by: Lee Chee Yang <chee.yang.lee@intel.com>